### ISSUE TITLE
Toggle-control does not load

### ISSUE THREAD

**Issue by chriskane** [Microsoft/vsts-extension-toggle-control#12]
Added the toggle controls to our forms but they do not load after the spinning wheel times out.  Seeing this message "toggle-control by ms-devlabs is taking longer than expected to load.  Learn More about this extension, including available support options".

**Comment by sferg-msft** [comment]
Thanks for the report.  Did you try this on hosted or onprem?

**Comment by chriskane** [comment]
This was for hosted, but I figured it out.  Our office web content filter was blocking GitHub.com.  Once I whitelisted this site the controls worked fine.

**Comment by sferg-msft** [comment]
Great, glad the issue was resolved.
