### ISSUE TITLE
Set default to Yes/True

### ISSUE THREAD

**Issue by ventil8** [Microsoft/vsts-extension-toggle-control#14]
Is there a way to set the default value to True rather than False?

**Comment by ostreifel** [comment]
Update the backing field's to default value to be true
### If on vsts
Use the [rules on the process administration page](https://docs.microsoft.com/en-us/vsts/release-notes/2017/aug-28-team-services#customizable-work-item-rules)

### If on tfs
Use the [TFS Process Template Editor](https://marketplace.visualstudio.com/items?itemName=KarthikBalasubramanianMSFT.TFSProcessTemplateEditor)

**Comment by ventil8** [comment]
That worked a treat, many thanks.
